name: Deploy Migrations to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: CHANGE_ME

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $STAGING_PROJECT_ID
          supabase db push
